### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './intent_prediction/paras.pkl'

### ISSUE THREAD

**Issue by 27182812** [mattc95/EmpHi#2]
Hello, it seems that we also need './intent_prediction/paras.pkl', which is not in your repo now.

**Comment by 27182812** [comment]
Maybe we should train BERT intent classifier firstly.

**Comment by mattc95** [comment]
Thank you for submitting this issue, the needed paras.pkl file download link will be attached in readme.md.

**Comment by 27182812** [comment]
That's great, thank you.
