### ISSUE TITLE
Your code seems to have a lot of problems. I can't run according to your instructions.

### ISSUE THREAD

**Issue by 27182812** [mattc95/EmpHi#3]
Hello, I tried to run the code according to your instructions, but I encountered a lot of problems. Maybe you can provide your result file or checkpoint, thanks!

**Comment by 27182812** [comment]
Maybe the problem is caused by the parlai version. Such as batch.observations, batch.text_lengths, etc.

**Comment by mattc95** [comment]
To whom has the same issue, please install the parlai version 1.0.0.

**Comment by 27182812** [comment]
Yes, I solved it. Thank you.
